# Site settings
title: "YouthMappers 10-Year Celebration - Bangladesh"
email: bsrittik@gmail.com
description: "Celebrating 10 years of mapping for resilience, togetherness, and change."
url: "https://brazilsinghrittik.github.io/youthmappers10"  # Replace with your actual GitHub Pages URL
twitter_username: youthmappers
github_username: brazilsinghrittik

# Build settings
markdown: kramdown

# Color settings (refined from your original colors)
color:
  primary-dark: '#1c3d75'         # Deep blue for headers/navs
  primary-light: '#2464aa'        # Your original blue
  background-light: '#f5f5f5'     # Soft light gray for better readability
  links: '#ffffff'                # White links on dark backgrounds
  links-light: '#dbe9f4'          # Light hover effect
  links-white: '#2464aa'          # Consistent blue for text links
  text: '#1a1a1a'                 # Dark gray text for contrast
  text-light: '#333333'           # Slightly lighter for secondary text

# Map tiles (OpenStreetMap default)
map_tiles:
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
  maxZoom: 19

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalink structure
permalink: /:title/
relative_permalinks: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:title/

# Plugins
plugins:
  - jekyll-gzip
