# Site settings
title: "YouthMappers 10-Year Celebration - Bangladesh"
email: bsrittik@gmail.com
description: "Celebrating 10 years of mapping for resilience, togetherness, and change."
url: "https://brazilsinghrittik.github.io/youthmappers10"  # Replace with your actual GitHub Pages URL
twitter_username: youthmappers
github_username: brazilsinghrittik

# Build settings
markdown: kramdown

# Color settings (customize freely)
color:
  primary-dark: '#e63946'           # A bold red (optional theme)
  primary-light: '#f1faee'          # Soft light
  background-light: '#ffffff'
  links: '#1d3557'
  links-light: '#a8dadc'
  links-white: '#457b9d'
  text: '#222'
  text-light: '#555'

# Map tiles (keep default or customize with Mapbox if needed)
map_tiles:
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
  maxZoom: 19

# Files to ignore
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalink settings
permalink: /:title/
relative_permalinks: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:title/

# Plugins
plugins:
  - jekyll-gzip
